name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install deps
        run: |
          poetry install --no-interaction --no-root

      - name: Lint & type-check
        run: |
          poetry run ruff check .
          poetry run mypy

      - name: Run tests
        run: |
          poetry run pytest --cov=budget_app --cov-report=term-missing
